### ISSUE TITLE
Version 2.1.2 throws exception on /env actuator for unresolvable properties

### ISSUE THREAD

**Issue by thorntonrp** [ulisesbocchio/jasypt-spring-boot#156]
[demo-jasypt.zip](https://github.com/ulisesbocchio/jasypt-spring-boot/files/3593081/demo-jasypt.zip)

Version 2.1.2 breaks the /env actuator endpoint on all of my applications.

In the attached demo project, the presence of `jasypt-spring-boot-starter` causes `DemoAppplicationTests` to fail whereas removing it or backing it down to version 2.1.1 allows the test to succeed. The error on 2.1.2 occurs due to a failure to resolve a property from one of the property sources that has been overridden in the active profile. To preserve backward compatibility as well as Spring's default behavior, a failure to resolve the property should return the property expression instead of throwing  an exception.

**Comment by thorntonrp** [comment]
My debugging shows that `environment::resolveRequiredPlaceholders` from [DefaultPropertyResolver.java:38](https://github.com/ulisesbocchio/jasypt-spring-boot/blob/f8fa8a12190f3fe4f010aa49513a4670bba4d09a/jasypt-spring-boot/src/main/java/com/ulisesbocchio/jasyptspringboot/resolver/DefaultPropertyResolver.java#L38)  is to blame. 

```java
@Override
    public String resolvePropertyValue(String value) {
        return Optional.ofNullable(value)
                .map(environment::resolveRequiredPlaceholders)
                .filter(detector::isEncrypted)
                .map(resolvedValue -> {
```
Instead of mapping `environment::resolveRequiredPlaceholders`, I believe that it should be calling `environment::resolvePlaceholders` instead.

**Comment by ulisesbocchio** [comment]
Thanks, can you do a PR?

**Comment by ulisesbocchio** [comment]
fixed in code, will be in next release

**Comment by thorntonrp** [comment]
I'm still seeing this behavior when running against a build from the master branch. Is this fixed on master or on a branch? I've been swamped the last couple months, but I can submit a PR today if you'd like.

**Comment by thorntonrp** [comment]
The PR that I just submitted fixes the issue in which there are multiple application properties files and in which the properties for the default profile has unresolvable properties. The /actuator/env endpoint is designed to look at all the loaded properties files. Without this fix. the /env endpoint will throw a 500 error because the DefaultPropertyResolver will throw an exception if any of the properties cannot be resolved.

**Comment by thorntonrp** [comment]
The attached demo-jasypt.zip (linked in the first comment) demonstrates the error. Running the demo against a build that has the PR in place resolves the issue.

**Comment by ulisesbocchio** [comment]
Thank you I’ll check it out. I though I fixed but I think I changed it in a different place
